In [10]:
import torch
import numpy as np

In [11]:
# Create a 2x3 tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Repeat the tensor 2 times along the first dimension
x_repeated = x.repeat(2, 1)

print("Original tensor:\n", x)
print("Repeated tensor:\n", x_repeated)

Original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Repeated tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])


In [13]:
x=torch.zeros(2,3)
x.dtype

torch.float32

In [27]:
x = np.array([1,2])
x[0:1]

array([1])

In [24]:
x = np.expand_dims(np.expand_dims(x,axis=0),axis=0)

In [25]:
x.shape

(1, 1, 2)

array([[[1, 2]]])

In [34]:
a = 
("There is no batch left in " + 
". Consider to user iterators.begin() to rescan from the beginning of the iterators")
a

SyntaxError: invalid syntax (3925300182.py, line 1)